from Atividade import Relogio
if __name__ == '__main__':
    relogio1 = Relogio('Rolex', 15000, 2021)
    print("Objeto Criado:", relogio1)
    relogio2 = Relogio('Apple watch', 5000, 2023)
    print('Objeto Criado:', relogio2)
    print('- Relogio 1\nModelo:', relogio1.get_modelo())
    print('Valor:', relogio1.get_valor())
    print('Ano:', relogio1.get_ano())
    print('Relogio2\nModelo:', relogio2.get_modelo())
    print('Ano:',relogio2.get_ano())
    print('Valor:',relogio2.get_valor())
    relogio1.set_valor(-12000)
    print('Valor atualizado do relogio 1:', relogio1.get_valor())
    relogio1.set_modelo('Sansung')
    print('Modelo atualizado do relogio 1:', relogio1.get_modelo())
    relogio2.set_ano('Maju')
    print('Ano atualizado relogio 2 :', relogio2.get_ano())
    relogio2.aumentar_valor(-500)
    print('Valor atualizado relogio 2:', relogio2.get_valor())
    relogio2.set_modelo(98)
    print('Modelo atualizado relogio 2:', relogio2.get_modelo())
    relogio1.mostrar_dados()
    relogio2.mostrar_dados()